settings:
  database:
    driver: mysql
    host: 127.0.0.1
    port: 3306
    username: root
    password: 123456
    dbname: ginchat
    charset: utf8mb4
  redis:
    hosts: "127.0.0.1:6379"
    password: "123456"
    db: 0
    poolSize: 100
    minIdleConn: 100